InteractiveFamilyTree.RazorPage/Pages/Events/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using InteractiveFamilyTree.DTO.Models;
using InteractiveFamilyTree.DAO.IServices;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace InteractiveFamilyTree.RazorPage.Pages.Events
{
    [Authorize(Roles = "admin")]
    public class CreateModel : PageModel
    {
        private readonly IFamilyEventService _service;
        private readonly IFamilyTreeService _treeservice;

        public CreateModel(IFamilyEventService service, IFamilyTreeService treeservice)
        {
            _service = service;
            _treeservice = treeservice;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            ViewData["TreeId"] = new SelectList(await _treeservice.Get(), "Id", "FirstName");
            return Page();
        }

        [BindProperty]
        public FamilyEvent FamilyEvent { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || _service == null || FamilyEvent == null)
            {
                return Page();
            }
            await _service.AddAsync(FamilyEvent);

            return RedirectToPage("./Index");
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Events/Participants/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using InteractiveFamilyTree.DTO.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace InteractiveFamilyTree.RazorPage.Pages.Events.Participants
{
    [Authorize(Roles = "admin")]
    public class CreateModel : PageModel
    {
        private readonly InteractiveFamilyTree.DTO.Models.InteractiveFamilyTreeOfficalContext _context;

        public CreateModel(InteractiveFamilyTree.DTO.Models.InteractiveFamilyTreeOfficalContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["EventId"] = new SelectList(_context.FamilyEvents, "Id", "Description");
        ViewData["FamilyMemberId"] = new SelectList(_context.FamilyMembers, "Id", "FullName");
            return Page();
        }

        [BindProperty]
        public EventParticipant EventParticipant { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.EventParticipants == null || EventParticipant == null)
            {
                return Page();
            }

            _context.EventParticipants.Add(EventParticipant);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Events/Participants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using InteractiveFamilyTree.DTO.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace InteractiveFamilyTree.RazorPage.Pages.Events.Participants
{
    [Authorize(Roles = "admin")]
    public class DeleteModel : PageModel
    {
        private readonly InteractiveFamilyTree.DTO.Models.InteractiveFamilyTreeOfficalContext _context;

        public DeleteModel(InteractiveFamilyTree.DTO.Models.InteractiveFamilyTreeOfficalContext context)
        {
            _context = context;
        }

        [BindProperty]
      public EventParticipant EventParticipant { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.EventParticipants == null)
            {
                return NotFound();
            }

            var eventparticipant = await _context.EventParticipants.FirstOrDefaultAsync(m => m.Id == id);

            if (eventparticipant == null)
            {
                return NotFound();
            }
            else 
            {
                EventParticipant = eventparticipant;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.EventParticipants == null)
            {
                return NotFound();
            }
            var eventparticipant = await _context.EventParticipants.FindAsync(id);

            if (eventparticipant != null)
            {
                EventParticipant = eventparticipant;
                _context.EventParticipants.Remove(EventParticipant);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Events/Participants/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using InteractiveFamilyTree.DTO.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace InteractiveFamilyTree.RazorPage.Pages.Events.Participants
{
    [Authorize(Roles = "admin")]
    public class DetailsModel : PageModel
    {
        private readonly InteractiveFamilyTree.DTO.Models.InteractiveFamilyTreeOfficalContext _context;

        public DetailsModel(InteractiveFamilyTree.DTO.Models.InteractiveFamilyTreeOfficalContext context)
        {
            _context = context;
        }

      public EventParticipant EventParticipant { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.EventParticipants == null)
            {
                return NotFound();
            }

            var eventparticipant = await _context.EventParticipants.FirstOrDefaultAsync(m => m.Id == id);
            if (eventparticipant == null)
            {
                return NotFound();
            }
            else 
            {
                EventParticipant = eventparticipant;
            }
            return Page();
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Events/Participants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InteractiveFamilyTree.DTO.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace InteractiveFamilyTree.RazorPage.Pages.Events.Participants
{
    [Authorize(Roles = "admin")]
    public class EditModel : PageModel
    {
        private readonly InteractiveFamilyTree.DTO.Models.InteractiveFamilyTreeOfficalContext _context;

        public EditModel(InteractiveFamilyTree.DTO.Models.InteractiveFamilyTreeOfficalContext context)
        {
            _context = context;
        }

        [BindProperty]
        public EventParticipant EventParticipant { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.EventParticipants == null)
            {
                return NotFound();
            }

            var eventparticipant =  await _context.EventParticipants.FirstOrDefaultAsync(m => m.Id == id);
            if (eventparticipant == null)
            {
                return NotFound();
            }
            EventParticipant = eventparticipant;
           ViewData["EventId"] = new SelectList(_context.FamilyEvents, "Id", "Description");
           ViewData["FamilyMemberId"] = new SelectList(_context.FamilyMembers, "Id", "FullName");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(EventParticipant).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EventParticipantExists(EventParticipant.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool EventParticipantExists(int id)
        {
          return (_context.EventParticipants?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Events/Participants/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using InteractiveFamilyTree.DTO.Models;
using InteractiveFamilyTree.DAO.IServices;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using System.Linq.Expressions;

namespace InteractiveFamilyTree.RazorPage.Pages.Events.Participants
{
    [Authorize(Roles = "admin")]
    public class IndexModel : PageModel
    {
        private readonly IEventParticipantService _service;
        private readonly IFamilyMemberService _familyMemberService;

        public IndexModel(IEventParticipantService service, IFamilyMemberService familyMemberService)
        {
            _service = service;
            _familyMemberService = familyMemberService;
        }

        public IList<EventParticipant> EventParticipant { get;set; } = default!;



        public async Task OnGetAsync(int? id, int? treeId)
        {
            if (_service != null)
            {
                EventParticipant = await _service.Get(p => p.EventId == id,
                    includeProperties: new Expression<Func<EventParticipant, object>>[]
                        {
                            f => f.Event,
                            f => f.FamilyMember
                        });
            }
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Events/User/Participants/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using InteractiveFamilyTree.DTO.Models;
using InteractiveFamilyTree.DAO.IServices;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace InteractiveFamilyTree.RazorPage.Pages.Events.User.Participants
{
    [Authorize(Roles = "member,manager")]
    public class IndexModel : PageModel
    {
        private readonly IEventParticipantService _service;
        private readonly IFamilyMemberService _familyMemberService;

        public IndexModel(IEventParticipantService service, IFamilyMemberService familyMemberService)
        {
            _service = service;
            _familyMemberService = familyMemberService;
        }

        public IList<EventParticipant> EventParticipant { get; set; } = default!;

        public int EventId { get; set; }

        public int FamilyMemberId { get; set; }

        public string Role { get; set; } = null;

        public async Task<IActionResult> OnGetAsync(int eventId, bool? error)
        {
            if (error == true)
            {
                TempData["Message"] = "All family member have been added!!!";
            }

            int treeId = SessionHelper.GetIntFromSession(HttpContext.Session, "treeId");
            await CheckRole(treeId, eventId);

            if (Role == null || Role == "") return RedirectToPage("/Index");

            if (treeId == 0)
            {
                return NotFound();
            }

            if (_service != null || eventId != 0)
            {
                EventId = eventId;
                var list = (await _service.Get(
                    p => p.EventId == eventId,
                    p => p.OrderBy(p => p.FamilyMemberId),
                    p => p.FamilyMember, p => p.Event)).AsQueryable();
                EventParticipant = list.Where(e => e.FamilyMember.Status == true).ToList();
            }
            return Page();
        }

        public async Task<IActionResult> OnGetCreate(int eventId)
        {
            int treeId = SessionHelper.GetIntFromSession(HttpContext.Session, "treeId");
            await CheckRole(treeId, eventId);

            if (Role == null || Role == "") return RedirectToPage("/Index");
            int id = int.Parse(((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.Sid).Value);
            if (id != 0)
            {
                EventParticipant participant = new EventParticipant { EventId = eventId, FamilyMemberId = id, Status = "Confirmed" };
                await _service.AddAsync(participant);
            }
            return RedirectToAction(nameof(OnGetAsync), new { eventId = eventId });
        }

        public async Task<IActionResult> OnGetEdit(int eventId, int id)
        {
            int treeId = SessionHelper.GetIntFromSession(HttpContext.Session, "treeId");
            await CheckRole(treeId, eventId);

            if (Role == null || Role == "") return RedirectToPage("/Index");

            if (id != 0)
            {
                var participant = await _service.GetByID(id);
                if (participant != null)
                {
                    if (participant.Status == "") participant.Status = "Invited";
                    if (participant.Status != "Invited")
                    {
                        if (participant.Status == "Confirmed")
                        {
                            participant.Status = "Attended";
                        }
                        else participant.Status = "Confirmed";
                    }
                    await _service.Update(participant);
                }
            }
            return RedirectToAction(nameof(OnGetAsync), new { eventId = eventId});
        }

        public async Task<IActionResult> OnGetAccept(int eventId, int id)
        {
            int treeId = SessionHelper.GetIntFromSession(HttpContext.Session, "treeId");
            await CheckRole(treeId, eventId);

            if (Role == null || Role == "") return RedirectToPage("/Index");

            if (id != 0)
            {
                var participant = await _service.GetByID(id);
                if (participant != null)
                {
                    participant.Status = "Confirmed";
                    await _service.Update(participant);
                }
            }
            return RedirectToAction(nameof(OnGetAsync), new { eventId = eventId });
        }

        public async Task<IActionResult> OnGetDelete(int eventId, int id)
        {
            int treeId = SessionHelper.GetIntFromSession(HttpContext.Session, "treeId");
            await CheckRole(treeId, eventId);

            if (Role == null || Role == "") return RedirectToPage("/Index");

            if (id != 0)
            {
                await _service.Delete(id);
            }
            return RedirectToAction(nameof(OnGetAsync), new { eventId = eventId});
        }

        public async Task CheckRole(int treeId, int eventId)
        {
            int id = int.Parse(((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.Sid).Value);
            var check = await _familyMemberService.Get(f => f.MemberId == id && f.TreeId == treeId);
            if( check != null && check.Count() > 0)
            {
                Role = check.FirstOrDefault().Role;
            }
            if (Role == "member")
            {
                FamilyMemberId = check.FirstOrDefault().Id;
                if ((await _service.Get(p => p.FamilyMemberId == FamilyMemberId && p.EventId == eventId)).Count() > 0)
                {
                    Role = "Added Member";
                }
            }
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Events/User/Participants/Create.cshtml
@page
@model InteractiveFamilyTree.RazorPage.Pages.Events.User.Participants.CreateModel

@{
    ViewData["Title"] = "Add Member";
}

<h1>Add Member</h1>

<h4>EventParticipant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventParticipant.FamilyMemberId" class="control-label">Family Member</label>
                <select asp-for="EventParticipant.FamilyMemberId" class ="form-control" asp-items="ViewBag.FamilyMemberId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index" asp-route-eventId="@TempData["eventId"]">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InteractiveFamilyTree.RazorPage/Pages/Events/User/Participants/Index.cshtml
@page
@model InteractiveFamilyTree.RazorPage.Pages.Events.User.Participants.IndexModel

@{
    ViewData["Title"] = "Participant List";
}

<style>
    .button-link {
        display: inline-block;
        padding: 10px 20px;
        background-color: white;
        color: black;
        text-decoration: none;
        border-radius: 4px;
        border: none;
        cursor: pointer;
        width: 100%;
    }
</style>
<h1>Participant List</h1>

<p>
    <a asp-page="/Events/User/Index">Back to List</a>
</p>

@if (Model.Role == "manager")
{
    <p>
        <button class="btn btn-primary">
            <a asp-page="Create" asp-route-eventId="@Model.EventId" style="color:white; text-decoration:none;">Add New</a>
        </button>
    </p>
}else if (Model.Role == "member"){
    <p>
        <button class="btn btn-primary">
            <a asp-page-handler="Create" asp-route-eventId="@Model.EventId" style="color:white; text-decoration:none;">Join event</a>
        </button>
    </p>
}
else
{
    <br />
}
@if (TempData["Message"] != null)
{
    <div class="alert alert-danger">@TempData["Message"]</div>
}
<table class="table">
    <thead>
        <tr>
            <th class="text-center">No. </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.EventParticipant[0].FamilyMember)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.EventParticipant[0].Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            int count = 1;
        }
        @foreach (var item in Model.EventParticipant)
        {
            <tr>
                <td class="text-center">@count</td>
                <td class="text-center">
                        <a asp-page="/FamilyMemberPage/Details" class="button-link" asp-route-id="@item.Id" style="color: black; text-decoration:none;">@Html.DisplayFor(modelItem => item.FamilyMember.FullName)</a>
                </td>
                <td class="text-center"> 
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @if (Model.Role == "manager")
                    {
                        if (item.Status != "Invited")
                        {
                            <button class="btn btn-primary">
                                <a asp-page-handler="Edit" asp-route-id="@item.Id" asp-route-eventId="@Model.EventId" style="color: white; text-decoration: none">Edit</a>
                            </button>
                        }
                        <button class="btn btn-primary">
                            <a asp-page-handler="Delete" asp-route-id="@item.Id" asp-route-eventId="@Model.EventId" style="color: white; text-decoration: none">Remove</a>
                        </button>
                    }
                    else if (Model.FamilyMemberId == item.FamilyMemberId)
                    {
                        if (item.Status == "Invited")
                        {
                            <button class="btn btn-primary">
                                <a asp-page-handler="Accept" asp-route-id="@item.Id" asp-route-eventId="@Model.EventId" style="color: white; text-decoration: none">Accept</a>
                            </button>
                        }
                        <button class="btn btn-primary">
                            <a asp-page-handler="Delete" asp-route-id="@item.Id" asp-route-eventId="@Model.EventId" style="color: white; text-decoration: none">Remove</a>
                        </button>
                    }
                </td>
            </tr>
            count++;
        }
    </tbody>
</table>