InteractiveFamilyTree.RazorPage/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace InteractiveFamilyTree.RazorPage.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace InteractiveFamilyTree.RazorPage.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            //SessionHelper.RemoveStringFromSession(HttpContext.Session, "treeId");
            ////test
            //SessionHelper.SetStringToSession(HttpContext.Session, "treeId", "1");
            return Page();
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Login.cshtml.cs
using InteractiveFamilyTree.DAO.IServices;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace InteractiveFamilyTree.RazorPage.Pages
{
    [AllowAnonymous]
    public class LoginModel : PageModel
    {
        private readonly IFamilyMemberService _familyMemberService;
        private readonly IMemberService _service;
        private readonly IConfiguration _configuration;

        public LoginModel(IMemberService service, IFamilyMemberService familyMemberService)
        {
            _familyMemberService = familyMemberService;
            _service = service;
            _configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .Build();
        }

        [BindProperty]
        public string Email { get; set; } = null;

        [BindProperty]
        public string Password { get; set; } = null;

        public IActionResult OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToPage("/Index");
            }
            return Page();
        }
        public IActionResult OnGetLogout()
        {
            HttpContext.SignOutAsync("MyCookieAuth");
            // Clear all session data
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }

        public IActionResult OnGetRegister()
        {
            return RedirectToPage("/Register");
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid) return Page();
            IConfiguration config = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", true, true)
                .Build();
            var adEmail = config["DefaultAccount:Email"];
            var adPwd = config["DefaultAccount:Password"];
            var member = await _service.CheckLogin(Email, Password);
            // code to check username and password
            if (Email == adEmail && Password == adPwd)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Role, "admin")
                };
                var identity = new ClaimsIdentity(claims, "MyCookieAuth");
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync("MyCookieAuth", principal);
                return RedirectToPage("/Admin/Index");
            }

            if (member != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Sid, member.Id.ToString()),
                    new Claim(ClaimTypes.Name, member.FullName),
                    new Claim(ClaimTypes.Role, "member")
                };
                var identity = new ClaimsIdentity(claims, "MyCookieAuth");
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync("MyCookieAuth", principal);
                var tree = await _familyMemberService.Get(filter: e => e.MemberId == member.Id);
                if (tree.Count > 0)
                {
                    HttpContext.SignOutAsync("MyCookieAuth");
                    claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Sid, member.Id.ToString()),
                    new Claim(ClaimTypes.Name, member.FullName),
                    new Claim(ClaimTypes.Role, tree.FirstOrDefault().Role)
                };
                    identity = new ClaimsIdentity(claims, "MyCookieAuth");
                    principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync("MyCookieAuth", principal);
                    SessionHelper.SetObjectAsJson(HttpContext.Session, "treeId", tree.FirstOrDefault().TreeId);
                }
                return RedirectToPage("/Index");
            }
            else if (IsValidLoginAdmin(Email, Password))
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, "Admin"),
                    new Claim(ClaimTypes.Role, "admin")
                };
                var identity = new ClaimsIdentity(claims, "MyCookieAuth");
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync("MyCookieAuth", principal);
                return RedirectToPage("/Index");
            }
            else
            {
                TempData["Message"] = "Invalid username or password.";
                return Page();
            }
        }

        private bool IsValidLoginAdmin(string email, string password)
        {
            string adminEmail = _configuration.GetValue<string>("AdminCredentials:Email");
            string adminPassword = _configuration.GetValue<string>("AdminCredentials:Password");

            return (email == adminEmail && password == adminPassword);
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace InteractiveFamilyTree.RazorPage.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Register.cshtml.cs
using InteractiveFamilyTree.DAO.IServices;
using InteractiveFamilyTree.DTO.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace InteractiveFamilyTree.RazorPage.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly IMemberService _memberService;

        public RegisterModel(IMemberService memberService)
        {
            _memberService = memberService;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Member Member { get; set; } = default!;
        [BindProperty]
        public string? emailError { get; set; } = null;
        [BindProperty]
        public string? phoneError { get; set; } = null;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || _memberService == null || Member == null)
            {
                return Page();
            }
            if (await _memberService.CheckPhone(Member.Phone) != null)
            {
                phoneError = "This phone number is existed!";
            }
            if (await _memberService.CheckEmail(Member.Email) != null)
            {
                emailError = "This email is existed!";
            }
            if (emailError != null && phoneError != null)
            {
                return Page();
            }
            Member.Id = 100;
            await _memberService.AddAsync(Member);
            return RedirectToPage("./Login");
        }
        public async Task<int> newId()
        {
            int id = (await _memberService.Get()).Count();
            while((await _memberService.Get(m => m.Id == id)).Count() > 0)
            {
                id++;
            }
            return id;
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/UserEvent.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using InteractiveFamilyTree.DTO.Models;
using InteractiveFamilyTree.DAO.IServices;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json.Linq;
using InteractiveFamilyTree.DAO.Services;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using InteractiveFamilyTree.RazorPage.Paging;

namespace InteractiveFamilyTree.RazorPage.Pages
{
    [Authorize(Roles = "member,admin,manager")]
    public class UserEventModel : PageModel
    {
        private readonly IFamilyEventService _service;
        private readonly IFamilyMemberService _familyMemberService;
        private readonly IEventParticipantService _eventParticipantService;
        private readonly IConfiguration Configuration;

        public UserEventModel(IFamilyEventService service, IFamilyMemberService familyMemberService, IConfiguration configuration, IEventParticipantService eventParticipantService)
        {
            _service = service;
            _familyMemberService = familyMemberService;
            Configuration = configuration;
            _eventParticipantService = eventParticipantService;
        }

        public PaginatedList<EventNotify> Notifies { get; set; } = default!;

        public string? Search { get; set; } = null;

        public string NameSort { get; set; }
        public string DateSort { get; set; }
        public string StatusSort { get; set; }
        public string CurrentFilter { get; set; }
        public string FilterType { get; set; }
        public string CurrentSort { get; set; }

        public string Role { get; set; } = null;

        public class EventNotify
        {
            public int EventId { get; set; }
            public string EventName { get; set; }
            public DateTime Date { get; set; }
            public bool Status { get; set; }
            public string MemberStatus { get; set; }
        }

        public async Task<IActionResult> OnGetAsync(string sortOrder, string currentFilter, string searchString, int? pageIndex)
        {
            int treeId = HttpContext.Session.GetIntFromSession("treeId");
            var member = await CheckRole(treeId);

            CurrentSort = sortOrder;
            NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            DateSort = sortOrder == "Date" ? "date_desc" : "Date";
            StatusSort = sortOrder == "status" ? "status_desc" : "status";

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            CurrentFilter = searchString;

            if (Role == null || Role == "") return RedirectToPage("/index");
            if (treeId == 0)
            {
                return RedirectToPage("/index");
            }

            //if (search != null)
            //{
            //    FamilyEvent = await _service.Get(e => e.TreeId == treeId && e.Name.ToLower().Contains(search.ToLower()),
            //        orderBy: e => e.OrderByDescending(e => e.Status).ThenBy(e => e.Date).ThenBy(e => e.Type),
            //        includeProperties: e => e.Tree);
            //}
            //else
            //{
            //    FamilyEvent = await _service.Get(e => e.TreeId == treeId,
            //        orderBy: e => e.OrderByDescending(e => e.Status).ThenBy(e => e.Date).ThenBy(e => e.Type),
            //        includeProperties: e => e.Tree);
            //}
            var eventList = await _service.Get(e => e.TreeId == treeId);
            var eventJoinedList = await _eventParticipantService.Get(p => p.FamilyMemberId == member.Id);
            List<EventNotify>? listTemp = new List<EventNotify>();
            foreach(var eventJoined in eventJoinedList)
            {
                foreach (var events in eventList)
                {
                    if (eventJoined.EventId == events.Id)
                    {
                        var notify = new EventNotify
                        {
                            EventId = events.Id,
                            EventName = events.Name,
                            Date = events.Date,
                            Status = events.Status,
                            MemberStatus = eventJoined.Status

                        };
                        listTemp.Add(notify);
                    }
                }
            }

            IQueryable<EventNotify> list = listTemp.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                list = list.Where(s => s.EventName.ToLower().Contains(searchString.ToLower()));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    list = list.OrderByDescending(c => c.EventName);
                    break;
                case "Date":
                    list = list.OrderBy(c => c.Date);
                    break;
                case "date_desc":
                    list = list.OrderByDescending(c => c.Date);
                    break;
                case "status_desc":
                    list = list.OrderByDescending(c => c.Status);
                    break;
                case "status":
                    list = list.OrderBy(c => c.Status);
                    break;
                default:
                    list = list.OrderBy(c => c.EventName);
                    break;
            }
            var pageSize = Configuration.GetValue("PageSize", 4);
            Notifies = await PaginatedList<EventNotify>.CreateAsync(
                list.AsNoTracking(), pageIndex ?? 1, pageSize);
            return Page();
        }

        public async Task<FamilyMember> CheckRole(int treeId)
        {
            int id = int.Parse(((ClaimsIdentity)User.Identity).FindFirst(ClaimTypes.Sid).Value);
            var check = await _familyMemberService.Get(f => f.MemberId == id && f.TreeId == treeId);
            if (check != null && check.Count() > 0)
            {
                Role = check.FirstOrDefault().Role;
                return check.FirstOrDefault();
            }
            return null;
        }

        public async Task<IActionResult> OnGetAccept(int eventId)
        {
            int treeId = SessionHelper.GetIntFromSession(HttpContext.Session, "treeId");
            var member = await CheckRole(treeId);

            if (Role == null || Role == "") return RedirectToPage("/Index");

            if (member.Id != 0)
            {
                var participant = (await _eventParticipantService.Get(p => p.FamilyMemberId == member.Id && p.EventId == eventId)).FirstOrDefault();
                if (participant != null)
                {
                    participant.Status = "Confirmed";
                    await _eventParticipantService.Update(participant);
                }
            }
            return RedirectToAction(nameof(OnGetAsync));
        }

        public async Task<IActionResult> OnGetDelete(int eventId)
        {
            int treeId = SessionHelper.GetIntFromSession(HttpContext.Session, "treeId");
            var member = await CheckRole(treeId);

            if (Role == null || Role == "") return RedirectToPage("/Index");
            var participant = (await _eventParticipantService.Get(p => p.FamilyMemberId == member.Id && p.EventId == eventId)).FirstOrDefault();

            if (participant.Id != 0)
            {
                await _eventParticipantService.Delete(participant.Id);
            }
            return RedirectToAction(nameof(OnGetAsync));
        }
    }
}

InteractiveFamilyTree.RazorPage/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<style>

    .text-center1 {
        text-align: center;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        -ms-transform: translate(-50%, -50%);
        -webkit-transform: translate(-50%, -50%);
        border: 2px solid white;
        padding: 20px;
    }
    .text-center1 h1 {
        font-weight: bold;
        color: white;
    }
</style>
<body style="background-color: lightblue;">
    <div class="text-center1">
        <h1 class="display-4">FamilyBranches.com</h1>
    </div>
</body>

InteractiveFamilyTree.RazorPage/Pages/Login.cshtml
@page
@model InteractiveFamilyTree.RazorPage.Pages.LoginModel
@{
    ViewData["Title"] = "Login";
}
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <style>
        .body1 {
            font-family: Arial, sans-serif;
            background-color: #f1f1f1;
            background-image: url("/images/hand-drawn-floral-background_23-2149011038.jpg");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .container1 {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            margin-top: 100px;
        }

        .h1-login {
            text-align: center;
            margin-bottom: 20px;
        }

        .label-login {
            font-weight: bold;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 3px;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #4caf50;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            display: block;
            margin: 0 auto;
        }

        .validation-error {
            color: #ff0000;
            font-size: 12px;
            margin-top: 5px;
        }

        .error-message {
            color: #ff0000;
            font-size: 14px;
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body class="body1">
    <div class="container1">
        <h1 class="h1-login">Login</h1>

        <form method="post">
            <div>
                <label class="label-login" for="Email">Email</label>
                <input type="text" name="email" value="@TempData["email"]" required />
            </div>
            <div>
                <label class="label-login" for="Password">Password</label>
                <input name="password" type="password" value="@TempData["password"]" required />
            </div>
            @if (TempData["Message"] != null)
            {
                <div class="error-message">@TempData["Message"]</div>
            }
            <div>
                <input type="submit" value="Login" />
            </div>
            @*<img src="https://cdn-icons-png.flaticon.com/512/552/552721.png" alt="Image">*@
        </form>
        <br />
        <div>
            <a class="" asp-page="/login" asp-page-handler="Register">Register</a>
        </div>
    </div>
</body>
</html>

InteractiveFamilyTree.RazorPage/Pages/Register.cshtml
@page
@model InteractiveFamilyTree.RazorPage.Pages.RegisterModel
@{
    ViewData["Title"] = "Register";
}
<!DOCTYPE html>
<html>
<head>
    <title>Register Page</title>
    <style>
        .body1 {
            font-family: Arial, sans-serif;
            background-color: #f1f1f1;
            background-image: url("/images/hand-drawn-floral-background_23-2149011038.jpg");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .container1 {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            margin-top: 100px;
        }

        .h1-login {
            text-align: center;
            margin-bottom: 20px;
        }

        .label-login {
            font-weight: bold;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border-radius: 3px;
            border: 1px solid #ccc;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #4caf50;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 3px;
            cursor: pointer;
            display: block;
            margin: 0 auto;
        }

        .validation-error {
            color: #ff0000;
            font-size: 12px;
            margin-top: 5px;
        }

        .error-message {
            color: #ff0000;
            font-size: 14px;
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body class="body1">
    <div class="container1">
        <h1 class="h1-login">Register</h1>

        <form method="post">
            <div class="form-group">
                <label asp-for="Member.FullName" class="control-label"></label>
                <input asp-for="Member.FullName" class="form-control" />
                <span asp-validation-for="Member.FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Member.Image" class="form-control" type="hidden" value="https://cdn-icons-png.flaticon.com/512/552/552721.png" />
                <span asp-validation-for="Member.Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Member.Phone" class="control-label"></label>
                <input asp-for="Member.Phone" class="form-control" />
                <span asp-validation-for="Member.Phone" class="text-danger"></span>
            </div>
            <div class="error-message">@Model.phoneError</div>
            <div class="form-group">
                <label asp-for="Member.Email" class="control-label"></label>
                <input asp-for="Member.Email" class="form-control" type="email" />
                <span asp-validation-for="Member.Email" class="text-danger"></span>
            </div>
            <div class="error-message">@Model.emailError</div>
            <div class="form-group">
                <label asp-for="Member.Password" class="control-label"></label>
                <input asp-for="Member.Password" class="form-control" type="password" />
                <span asp-validation-for="Member.Password" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin: 20px 0px 20px 0px">
                <label asp-for="Member.Gender" class="control-label"></label>
                <label>
                    <input type="radio" asp-for="Member.Gender" value="true" /> Male
                    <span asp-validation-for="Member.Gender" class="text-danger"></span>
                </label>

                <label>
                    <input type="radio" asp-for="Member.Gender" value="false" /> Female
                    <span asp-validation-for="Member.Gender" class="text-danger"></span>
                </label>

            </div>
            <div class="form-group" style="margin-bottom: 20px">
                <label asp-for="Member.Birthday" class="control-label"></label>
                <input asp-for="Member.Birthday" class="form-control" type="date" min="1900-01-01" max="@DateTime.Now.Date.ToString("yyyy-MM-dd")" />
                <span asp-validation-for="Member.Birthday" class="text-danger"></span>
            </div>
            @if (TempData["Message"] != null)
            {
                <div class="error-message">@TempData["Message"]</div>
            }
            <div>
                <input type="submit" value="Register" />
            </div>
            @*<img src="https://cdn-icons-png.flaticon.com/512/552/552721.png" alt="Image">*@
        </form>
        <br />
        <div>
            <a class="" asp-page="/login" >Have an account? Login</a>
        </div>
    </div>
</body>
</html>

InteractiveFamilyTree.RazorPage/Pages/UserEvent.cshtml
@page
@model InteractiveFamilyTree.RazorPage.Pages.UserEventModel

@{
    ViewData["Title"] = "Invited Events";
}
<style>
    .button-link {
        display: inline-block;
        padding: 10px 20px;
        background-color: white;
        color: black;
        text-decoration: none;
        border-radius: 4px;
        border: none;
        cursor: pointer;
        width: 100%;
    }
</style>
<h1 class="text-center">Invited Events</h1>
@*<p>
    <a asp-page="/FamilyTreePage/User/Index">Back to Tree</a>
</p>*@
<form asp-page="/UserEvent" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name:
            <input type="text" name="SearchString" value="@Model.CurrentFilter" />
            <input type="submit" value="Search" class="btn btn-primary" /> |
            <a asp-page="/UserEvent">Back to full List</a>
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th class="text-center">No. </th>
            <th>
                <a asp-page="/UserEvent" asp-route-sortOrder="@Model.NameSort"
                   asp-route-currentFilter="@Model.CurrentFilter">
                    Event Name
                </a>
            </th>
            <th class="text-center">
                <a asp-page="/UserEvent" asp-route-sortOrder="@Model.DateSort"
                   asp-route-currentFilter="@Model.CurrentFilter">
                    Date
                </a>
            </th>
            <th class="text-center">
                <a asp-page="/UserEvent" asp-route-sortOrder="@Model.StatusSort"
                   asp-route-currentFilter="@Model.CurrentFilter">
                    EventStatus
                </a>
            </th>
            <th>
                Invitation
            </th>
            <th class="text-center"></th>
        </tr>
    </thead>
    <tbody>
        @{
            int count = 1;
        }
        @foreach (var item in Model.Notifies)
        {
            <tr>
                <td class="text-center">@count</td>
                <td>
                    <a asp-page="./Details" class="button-link" asp-route-id="@item.EventId" style="color: black; text-decoration:none;">@Html.DisplayFor(modelItem => item.EventName)</a>
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td class="text-center">
                    @if (item.Status == true)
                    {
                        if (item.Date > DateTime.Now)
                        {
                            <p>Pending</p>
                        }
                        else if (item.Date <= DateTime.Now)
                        {
                            <p>Ongoing</p>
                        }
                    }
                    else
                    {
                        if (item.Date > DateTime.Now)
                        {
                            <p>Canceled</p>
                        }
                        else if (item.Date < DateTime.Now)
                        {
                            <p>Completed</p>
                        }
                    }
                </td>
                <td>
                    @if (item.MemberStatus == "Invited")
                    {
                        <p>Not Accepted</p>
                    }
                    else
                    {
                        @Html.DisplayFor(modelItem => item.MemberStatus)
                    }
                </td>
                <td>
                    @if (item.MemberStatus == "Invited")
                    {
                        <button class="btn btn-primary">
                            <a asp-page-handler="Accept" asp-route-eventId="@item.EventId" style="color: white; text-decoration: none">Accept</a>
                        </button>
                    }
                    <button class="btn btn-primary">
                        <a asp-page-handler="Delete" asp-route-eventId="@item.EventId" style="color: white; text-decoration: none">Remove</a>
                    </button>

                </td>
            </tr>
            count++;
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.Notifies.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.Notifies.HasNextPage ? "disabled" : "";
}

<a asp-page="/UserEvent"
   asp-route-sortOrder="@Model.CurrentSort"
   asp-route-pageIndex="@(Model.Notifies.PageIndex - 1)"
   asp-route-currentFilter=@Model.CurrentFilter
   class="btn btn-primary @prevDisabled">
    Previous
</a>

<a asp-page="/UserEvent"
   asp-route-sortOrder="@Model.CurrentSort"
   asp-route-pageIndex="@(Model.Notifies.PageIndex + 1)"
   asp-route-currentFilter=@Model.CurrentFilter
   class="btn btn-primary @nextDisabled">
    Next
</a>